# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
